/**
 * Brother's Bites — Comprehensive Master SEO Keywords Dictionary
 * Covering Official Menu Items, Sips & Juices, Upcoming Bites, Local Cox's Bazar Landmarks,
 * Nationwide Foodie Searches, Intent Phrases, and Bengali/Banglish Phonetics.
 */

// 1. Core Brand & Misspellings / Variations
const brandVariations = [
  "Brother's Bites",
  "Brothers Bites",
  "BrothersBites",
  "Brothers Bite",
  "Brother Bite",
  "Brother's Bites BD",
  "Brothers Bites Bangladesh",
  "Brothers Bites Cox's Bazar",
  "Brother's Bites Coxs Bazar",
  "Brothers Bites Marine Drive",
  "Brother's Bites Sonar Para",
  "Brothers Bites Sonar Para Beach",
  "BBites",
  "BBites BD",
  "BBites Cox's Bazar",
  "BBites Restaurant",
  "Brothers Bites Fast Food",
  "Brothers Bites Cafe",
  "Brothers Bites Street Food",
  "Brothers Bites Official Website",
  "Brothers Bites Online Order",
  "Brothers Bites Menu",
  "Brothers Bites Price",
  "Brothers Bites Location",
  "Brothers Bites Contact",
  "Brothers Bites Review",
  "Every Bite Feels Like a Breeze",
  "Bites Sips Brotherhood",
];

// 2. Official Menu Items & Specials (From Official Menu Card)
const officialMenuItems = [
  // Bites
  "Chicken Momo",
  "Chicken Momos",
  "Juicy Chicken-filled Steamed Dumplings",
  "Steamed Chicken Momo",
  "Fried Chicken Momo",
  "Crispy Fried Chicken Momo",
  "Fried Momo 7 pcs",
  "Chicken Momo 7 pcs ৳80",
  "Chicken Momo 7 pcs ৳120",
  "Chicken Nuggets",
  "Chicken Nuggets 5 pcs",
  "Golden Crispy Chicken Nuggets",
  "Chicken Nuggets ৳70",
  "Chicken Nuggets ৳110",
  "Chicken Popcorn",
  "Chicken Popcorn 100g",
  "Crispy Bite-sized Chicken",
  "Chicken Popcorn ৳90",
  "Brother's Specials Chicken Momo",
  "Brother's Specials Chicken Nuggets",
  "Brother's Specials Chicken Popcorn",

  // Sips & Signature Juices / Beverages
  "Lemon Chill",
  "Lemon Chill Drink",
  "Refreshing Chilled Lemon Drink",
  "Lemon Chill ৳59",
  "Chilled Lemonade Cox's Bazar",
  "Mango Magic",
  "Mango Magic Juice",
  "Sweet Refreshing Mango Drink",
  "Mango Magic ৳99",
  "Fresh Mango Juice Marine Drive",
  "Dragoo Blast",
  "Dragoo Blast Drink",
  "Bold and Refreshing Dragon-Fruit Drink",
  "Dragon Fruit Juice",
  "Dragoo Blast ৳109",
  "Pink Dragon Fruit Juice",
  "Coco Delight",
  "Coco Delight Drink",
  "Creamy Refreshing Coconut Drink",
  "Coconut Shake",
  "Coco Delight ৳129",
  "Beach Coconut Drink",
  "Freshly Brewed Hot Tea",
  "Tea ৳20",
  "Hot Dudh Cha",
  "Signature Caramel Tea",
  "Caramel Cha",
  "Rich and Aromatic Coffee",
  "Coffee ৳40",
  "Hot Milk Coffee",
  "Creamy Coffee",
];

// 3. Upcoming Specialties & High-Demand Food Items
const upcomingAndPopularDishes = [
  // Haleem
  "Haleem",
  "Shahi Haleem",
  "Special Beef Haleem",
  "Chicken Haleem",
  "Slow Cooked Haleem",
  "Mutton Haleem",
  "Best Haleem in Cox's Bazar",
  "Haleem with Fried Onions & Ginger",
  "Evening Hot Haleem",
  "Cox's Bazar Haleem",

  // Fuchka & Street Delicacies
  "Yogurt Fuchka",
  "Dahi Fuchka",
  "Special Dahi Fuchka",
  "Sweet & Tangy Yogurt Fuchka",
  "Crispy Fuchka",
  "Pani Puri",
  "Dahi Puri",
  "Gol Gappa",
  "Spicy Naga Fuchka",
  "Tamarind Chutney Fuchka",
  "Cox's Bazar Street Fuchka",

  // Seafood Bites
  "Crispy Shrimp Fry",
  "Coastal Prawn Fry",
  "Golden Shrimp Fry",
  "Butterfly Prawns",
  "Crispy Calamari",
  "Deep Fried Squid",
  "Crab Fry",
  "Finger Fish Fry",
  "Fish & Chips",
  "Coastal Seafood Platter",

  // Thai & Asian Bites
  "Thai Spicy Chicken",
  "Spicy Basil Chicken",
  "Chili Chicken Bites",
  "Thai Fried Chicken",
  "Naga Chicken Wings",
  "BBQ Chicken Wings",
  "Chicken Strips",

  // Burgers & Fast Food
  "Crispy Chicken Burger",
  "Beef Burger",
  "Cheese Burger",
  "Smash Burger",
  "Double Patty Burger",
  "Street Style Burger",
  "Fast Food Burger Cox's Bazar",
  "Fried Chicken",
  "Crispy Fried Chicken",
  "Hot & Spicy Fried Chicken",
  "Crunchy Chicken Tenders",
  "French Fries",
  "Masala Fries",
  "Loaded Fries",

  // Juices & Smoothies
  "Fresh Fruit Juice",
  "Cold Pressed Juice",
  "Mocktails",
  "Strawberry Shake",
  "Chocolate Milkshake",
  "Oreo Shake",
  "Cold Coffee with Ice Cream",
];

// 4. Local Cox's Bazar Geographical & Landmarks
const coxBazarLocations = [
  "Marine Drive Cox's Bazar",
  "Sonar Para Beach",
  "Sonar Para Marine Drive",
  "Inani Beach",
  "Himchari",
  "Himchori Waterfall",
  "Kolatoli Beach",
  "Kolatoli Point",
  "Sugandha Beach",
  "Laboni Beach",
  "Darianagar",
  "Ukhia",
  "Teknaf Marine Drive",
  "Cox's Bazar Sea Beach",
  "Longest Sea Beach in the World",
  "Cox's Bazar Highway",
  "Marine Drive Road Food Spots",
  "Sonarpara Bazar",
  "Inani Resort Area",
  "Marine Drive Sunset Point",
  "Sonar Para Beach Walkway",
  "Cox's Bazar Sadar",
];

// 5. Broader Nationwide Bangladesh & Travel / Tourism Search Terms
const travelAndNational = [
  "Cox's Bazar Tour Food Guide",
  "Best Food in Cox's Bazar",
  "Where to Eat in Cox's Bazar",
  "Cox's Bazar Street Food Tour",
  "Cox's Bazar Best Restaurant",
  "Top 10 Food Spots Cox's Bazar",
  "Marine Drive Evening Hangout",
  "Late Night Food Cox's Bazar",
  "Open Late Restaurant Marine Drive",
  "Family Restaurant Cox's Bazar",
  "Couple Friendly Cafe Cox's Bazar",
  "Best Fast Food in Bangladesh",
  "Street Food Bangladesh",
  "Bangladesh Coastal Cuisine",
  "Cox's Bazar Travel Foodie",
  "Food Bloggers Cox's Bazar",
  "Cox's Bazar Food Review",
  "Hygienic Street Food Cox's Bazar",
  "Affordable Restaurant Cox's Bazar",
  "Cheap Food Cox's Bazar",
  "Delicious Snacks Marine Drive",
  "Tourist Food Guide Bangladesh",
  "Dhaka to Cox's Bazar Food Guide",
  "Chittagong to Cox's Bazar Food Spots",
];

// 6. User Search Intent & Commercial Action Keywords
const searchIntents = [
  "Fast food restaurant near me",
  "Best momos near me",
  "Best chicken nuggets near me",
  "Best chicken popcorn near me",
  "Juice bar near Marine Drive",
  "Best restaurant near Marine Drive",
  "Cafe near Sonar Para beach",
  "Food near Inani beach",
  "Order food online Cox's Bazar",
  "Fast food delivery Marine Drive",
  "Best snacks near sea beach",
  "Tea stall Marine Drive",
  "Coffee shop Sonar Para beach",
  "Outdoor seating restaurant Cox's Bazar",
  "Sea view restaurant Cox's Bazar",
  "Beach view cafe Marine Drive",
  "Takeaway food Sonar Para",
  "Freshly cooked food Cox's Bazar",
  "Brother's Bites location map",
  "Brother's Bites phone number",
  "Brother's Bites opening hours",
  "Brother's Bites menu and prices",
];

// 7. Bengali & Banglish Phonetic Keywords (For Local Searches)
const bengaliAndPhonetic = [
  "ব্রাদার্স বাইটস",
  "ব্রাদার্স বাইটস কক্সবাজার",
  "ব্রাদার্স বাইট",
  "চিকেন মোমো",
  "ফ্রাইড চিকেন মোমো",
  "চিকেন নাগেটস",
  "চিকেন পপকর্ন",
  "লেমন চিল",
  "ম্যাংগো ম্যাজিক জুস",
  "ড্রাগু ব্লাস্ট জুস",
  "কোকো ডিলাইট",
  "ক্যারামেল চা",
  "হালিম কক্সবাজার",
  "দই ফুচকা",
  "চিংড়ি ফ্রাই",
  "বারবার্গার কক্সবাজার",
  "কক্সবাজার ফাস্ট ফুড",
  "কক্সবাজার সেরা মোমো",
  "চিকেন মোমো কক্সবাজার",
  "মেরিন ড্রাইভ রেস্টুরেন্ট",
  "সোনার পাড়া বিচ খাবার",
  "ইনানী বিচ খাবার",
  "কক্সবাজার স্ট্রিট ফুড",
  "কক্সবাজার সেরা রেস্তোরাঁ",
  "মেরিন ড্রাইভ ক্যাফে",
  "Brothers bites khabar",
  "Cox's bazar e bhalo khabar",
  "Momo khabo kothay",
  "Marine drive e bhalo restaurant",
  "Sonar para te bhalo khabar",
  "Doi fuchka kothay pabo",
  "Cox bazar er shera momo",
  "Coxs bazar fast food dokan",
  "Marine drive er cha er dokan",
  "Caramel cha kothay pawa jay",
  "Halim kothay bhalo pawa jay",
  "Lemon chill juice",
  "Dragon fruit juice cox bazar",
];

// Combine and generate systematic permutations
export const MASTER_SEO_KEYWORDS: string[] = Array.from(
  new Set([
    ...brandVariations,
    ...officialMenuItems,
    ...upcomingAndPopularDishes,
    ...coxBazarLocations,
    ...travelAndNational,
    ...searchIntents,
    ...bengaliAndPhonetic,
  ])
);

// Format as comma-separated meta keyword string
export const SEO_KEYWORDS_STRING = MASTER_SEO_KEYWORDS.join(', ');
